name: Push

on:
  push:
    branches: [main]

jobs:
  verify:
    uses: ./.github/workflows/verification.yml

  publish:
    needs: verify
    uses: ./.github/workflows/publishing.yml
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit

  deploy:
    needs: verify
    uses: ./.github/workflows/deployment.yml
    permissions:
      contents: read
      deployments: write
    secrets: inherit
