name: Push

on:
  push:
    branches: [main]

jobs:
  verify:
    permissions:
      contents: read
    uses: ./.github/workflows/verification.yml
    secrets: inherit

  publish:
    needs: verify
    uses: ./.github/workflows/publishing.yml
    concurrency: ${{ github.workflow }}-${{ github.ref }}-publish
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit

  deploy:
    needs: verify
    uses: ./.github/workflows/deployment.yml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy
      cancel-in-progress: true
    permissions:
      contents: read
      deployments: write
    secrets: inherit
