name: Snapshot publishing

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/yarnpkg/berry/issues/4014
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - run: yarn build:packages

      - run: yarn workspaces foreach -Apt --no-private version 0.0.0-snapshot.${{ github.run_number }}+$(git rev-parse --short HEAD) --immediate

      - run: scripts/publish-snapshot.sh
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
